### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by damianlluch** [maxpaynestory/ecommerce-nextjs-firebase#1]
Do you have any idea how to create an _app.tsx file in NextJS14 ? I haven't found a document and I need to define a provider for web3-react.js ?

Thanks

**Comment by maxpaynestory** [comment]
No idea, I am just a noob just like you.

**Comment by damianlluch** [comment]
I was able to do it, to add providers in Nextjs14 or 13, is through the layout.tsx file.

Best regards
